name: Testes Automatizados Cypress
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  testes:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Testar versão LOCAL
        run: npm test

      - name: Testar versão PUBLICADA na Web
        run: npx cypress run --config baseUrl=https://everaldo-barros.github.io/formulario-reserva-de-ingressos/